### ISSUE TITLE
Add maven coordinates to Vaadin directory

### ISSUE THREAD

**Issue by rfichtner** [xdev-software/vaadin-addon-template#31]
Vaadin directory now requires maven groupid to start with "org.vaadin.addons." to show the maven coordinates. 

See:
https://vaadin.com/directory/component/chip-combobox-for-vaadin

Looking for a way to have both: our groupid and the full listing on vaadin directory.

**Comment by AB-xdev** [comment]
Todo:
Vaadin Directory can now use Maven Central.

* Update Chip-Combobox / Sync with Maven
* Update the template so that we don't build the ZIP
  * Update Docs

**Comment by JohannesRabauer** [comment]
Right now it is not possible to update the chip-combobox, because the "New version from Maven"-Button is not available in the existing Component. Another Support-E-Mail was sent. We have to wait for an answer.

**Comment by JohannesRabauer** [comment]
https://vaadin.com/directory/component/chip-combobox-for-vaadin v3.1.0 has been published through maven. So it looks like it works. 
If the following issue are fixed, new version are released and this worked without explicit vaadin publishing, then we should close this issue and fix the "Setup"-Description (see https://github.com/xdev-software/vaadin-addon-template/wiki/Setup):
1. https://github.com/xdev-software/vaadin-date-range-picker/issues/34
2. https://github.com/xdev-software/vaadin-chip-combobox/issues/14

**Comment by AB-xdev** [comment]
#### I you are searching the "Edit" Button...

So after 10mins looking in panic for the edit button I found it when I clicked "back", returned to the component (Browser History Back) and scrolled down to the links section:

![grafik](https://user-images.githubusercontent.com/45384811/224637838-cc1fa376-54cd-424f-a036-e66b38889aa8.png)

**Comment by AB-xdev** [comment]
Fun Fact (6 hours later) when you now click on a component it opens the edit view. 😆

**Comment by AB-xdev** [comment]
Vaadin Directory syncing seems to work as expected for all 5 Vaadin components.

As there is nothing more to do, I'm closing the issue.
